### ISSUE TITLE
Use Egyptian Brackets

### ISSUE THREAD

**Issue by MrGallo** [SSadatmansoori/pbd-solutions-#1]
Please use Egyptian-brackets in your code.

**Meh:**
```java
public static void main(String[] args)
{
    System.out.println("Hello");
}
```

**Much Better:**
```java
public static void main(String[] args) {
    System.out.println("Hello");
}
```
See [Number 3](https://blog.codinghorror.com/new-programming-jargon/)https://github.com/SSadatmansoori/pbd-solutions-/blob/ef88820ec3c219f40615b76bd279c08f43352148/03/FirstProg.java#L1-L2

**Comment by SSadatmansoori** [comment]
done
